---
title: "In-class Excersice 04"
description: |
  A new article created using the Distill format.
author:
  - name: Bomin Kim 
    url: https://example.com/norajones
    affiliation: Spacely Sprockets
    affiliation_url: https://example.com/spacelysprokets
date: "`r Sys.Date()`"
output: distill::distill_article
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = TRUE, message = FALSE, warning = FALSE, fig.retina = 3)
```

# Getting Started

## Setting up R packages

To start with, [ggstatsplot]{https://indrajeetpatil.github.io/ggstatsplot/} and tidyverse packages will be launch using library().

```{r}
packages = c('ggstatsplot', 'tidyverse')
for (p in packages){
  if(!require(p, character.only = T)){
    install.packages(p)
  }
}
```

## Importing data

```{r}
exam <- read_csv("data/Exam_data.csv")
```

## Working with ggstatsplot

### ANOVA test

```{r}
ggbetweenstats(
  data = exam,
  x = RACE, 
  y = ENGLISH,
  type = "p",
  mean.ci = TRUE, 
  pairwise.comparisons = TRUE, 
  pairwise.display = "s",
  p.adjust.method = "fdr",
  messages = FALSE
)
```

```{r}
ggbetweenstats(
  data = exam,
  x = RACE, 
  y = ENGLISH,
  type = "np"
)
```

```{r}
ggbetweenstats(
  data = exam,
  x = RACE, 
  y = ENGLISH,
  type = "robust"
)
```

```{r}
set.seed(1234)

ggbetweenstats(
  data = exam,
  x = RACE, 
  y = ENGLISH,
  type = "bayes"
)
```